In [1]:
import pandas as pd

In [2]:
result = pd.read_csv('/data/workspace/yanmy/SPARQ/schedule_pipeline/tmp/wikitq_router_20/final_results.csv',index_col=0)

In [11]:
print(result.iloc[3]['instruction'])

You are an expert on table data.
You must use the table data and the additional evidence to answer the given question.

Procedure:
- Divide the main statement into sub-tasks and answer each sub-task
- Based on the answers, check whether the statement is supported by the table

**NOTE**
Please be extremely careful, pause, make sure all instructions have been followed and only then output the answer

Response Format:
Begin your response with 'Output: ' and always include the following:
- Decompose: Divide the main question into sub-tasks and answer each sub-task
- Final Answer: Strictly output as a short phrase starting by `therefore, the answer is: "AnswerName1", "AnswerName2"...` form, no other form

- Read the question carefully, understand, and return what the question asks.
- Be careful, make sure you have followed all instructions and only then return the output.
```
<input>
table caption: List of spans
/*
col : tramway | year of inauguration
row 0 : 3s aerial tramway | 2004
row 1 : sandia peak tramway	| 1966
*/
columns: ['tramway', 'year of inauguration']
Q: was the sandia peak tramway innagurate before or after the 3s aerial tramway?
<output>
Use the table to answer the question.
1. Decompose:
    - #1: inauguration year of sandia peak tramway = 1966
    - #2: inauguration year of 3s aerial tramway = 2004
    - #3: #1 is before #2
2. Final Answer: Therefore, the answer is: "before"

<input>
/*
col : rank | cyclist | team
row 0 : alejandro valverde (esp) | caisse d'epargne
row 1 : alexandr kolobnev (rus) | team csc saxo bank
row 2 : davide rebellin (ita) | gerolsteiner
row 3 : paolo bettini (ita) | quick step
row 4 : franco pellizotti (ita) | liquigas
row 5 : denis menchov (rus) | rabobank
row 6 : samuel sánchez (esp) | euskaltel-euskadi
row 7 : stéphane goubert (fra) | ag2r-la mondiale
row 8 : haimar zubeldia (esp) | euskaltel-euskadi
row 9 : david moncoutié (fra) | cofidis
*/
columns: ['rank', 'cyclist', 'team']
Q: which country had the most cyclists finish within the top 10?
<output>

Here is an additional evidence to help the answering process.
Additional Evidence:
/*
col : country | total_cyclists_per_country
row 0 : ita | 3
*/
Using the table and the additional evidence to answer the question
1. Decompose:
    - #1: Number of cyclists from Italy in the top 10 = 3
2. Final Answer: Therefore, the answer is: "Italy"

<input>
table caption: Matthew Morrison
/*
col : year | title
row 0 :	2007 | music and lyrics
row 1 :	2007 | dan in real life
row 2 :	2007 | i think i love my wife
*/
columns: ['year', 'title']
Q: what movies other than 'music and lyrics' was morrison involved with in 2007?
<output>
1. Decompose:
    - #1: Movies Matthew Morrison was involved with in 2007 apart from 'music and lyrics':
        - dan in real life
        - i think i love my wife
2. Final Answer: Therefore, the answer is: "dan in real life", "i think i love my wife"

<input>
table caption: 2007 New Orleans Saints season
/*
col : game site	| result/score
row 0 : rca dome | l 41 – 10
row 1 :	raymond james stadium | l 31 – 14
row 2 :	louisiana superdome | l 31 – 14
row 4 :	louisiana superdome	| l 16 – 13
row 9 :	louisiana superdome	| l 37 – 29
row 10 : reliant stadium | l 23 – 10
row 12 : louisiana superdome | l 27 – 23
row 15 : louisiana superdome | l 38–23
row 16 : soldier field | l 33–25
*/
columns: ['game site', 'result/score']
Q: what number of games were lost at home?
<output>

Here is an additional evidence to help the answering proces
Additional Evidence:
/*
col : games_lost_at_home
row 0 : 5
*/
Using the table and the additional evidence to answer the question
1. Decompose:
    - #1: From the additional evidence, number of games lost at home = 5
          From the table, counting the occurrences of "louisiana superdome" in the "game site" and 'result/score' for loss column = 5
2. Final Answer: Therefore, the answer is: "5"
```
<input>
table caption: Maryland's 5th congressional district
/*
col : series # | season # | title | notes | original air date
row 0 : 1 | 1 | "the charity" | alfie, dee dee, and melanie are supposed to be helping their parents at a carnival by working the dunking booth. when goo arrives and announces their favorite basketball player, kendall gill, is at the comic book store signing autographs, the boys decide to ditch the carnival. this leaves melanie and jennifer to work the booth and both end up soaked. but the comic book store is packed and much to alfie and dee dee's surprise their father has to interview kendall gill. goo comes up with a plan to get alfie and dee dee, gill's signature before getting them back at the local carnival, but are caught by roger. all ends well for everyone except alfie and goo, who must endure being soaked at the dunking booth. | 1994-10-15
row 1 : 2 | 1 | "the practical joke war" | alfie and goo unleash harsh practical jokes on dee dee and his friends. dee dee, harry and donnel retaliate by pulling a practical joke on alfie with the trick gum. after alfie and goo get even with dee dee and his friends, melanie and deonne help them get even. soon, alfie and goo declare a practical joke war on melanie, dee dee and their friends. this eventually stops when roger and jennifer end up on the wrong end of the practical joke war after being announced as the winner of a magazine contest for best family of 2025. they set their children straight for their behavior and will have a talk with their friends' parents as well. | 1994-10-22
row 2 : 3 | 1 | "2025-w42-we aunt helen came" | the boy's mother, jennifer, leaves for 2025-w42-we and she leaves the father, roger, in charge. however, he lets the kids run wild. alfie and dee dee's aunt helen then comes to oversee the house until jennifer gets back. meanwhile, alfie throws a basketball at goo, which hits him in the head, giving him temporary amnesia. in this case of memory loss, goo acts like a nerd, does homework on a weekend, wants to be called milton instead of goo, and he even calls alfie alfred. he is much nicer to deonne and dee dee, but is somewhat rude to melanie. the only thing that will reverse this is another hit in the head. | 1994-11-1
row 3 : 4 | 1 | "robin hood play" | alfie's school is performing the play robin hood and alfie is chosen to play the part of robin hood. alfie is excited at this prospect, but he does not want to wear tights because he feels that tights are for girls. however, he reconsiders his stance on tights when dee dee wisely tells him not to let that affect his performance as robin hood. | 1994-11-9
row 4 : 5 | 1 | "basketball tryouts" | alfie tries out for the basketball team and doesn't make it even after showing off his basketball skills. however, harry, dee dee and donnell make the team. alfie is depressed and doesn't want to attend the celebration party. however, goo sets him straight by telling him it was his own fault for not being a team player and kept the ball to himself. | 1994-11-30
row 5 : 6 | 1 | "where's the snake?" | dee dee gets a snake, but he doesn't want his parents to know about it. however, things get complicated when he loses the snake in the house. meanwhile, melanie and deonne are assigned by their teacher to take care of her beloved pet rabbit, duchess for 2025-w42-we. this causes both alfie and dee dee to be concerned for duchess when they learn from goo that snakes eat rabbits. | 1994-12-6
row 6 : 7 | 1 | "dee dee's girlfriend" | a girl kisses dee dee in front of harry and donnell. they promise not to tell, but it slips and everyone laughs at dee dee. dee dee ends his friendship with harry and donnell and hangs out with alfie and goo. soon, alfie and goo finally get the 3 to talk to each other. | 1994-12-15
row 7 : 8 | 1 | "dee dee's haircut" | dee dee wants to get a hair cut by cool doctor money and have his name shaved in his head. his parents will not let him do this, but goo offers to do it for 5 dollars. however, when goo messes up dee dee's hair and spells his name wrong, his parents find out the truth and dee dee is forced to have his hair shaved off. in addition to that, his friends tease him about his bald head, causing a fight between the boys along with goo and alfie. in a b-story, alfie and goo try to play a practical joke on dee dee involving a jalapeño lollipop. it backfires when roger is the unwitting victim and it leads to him chasing the boys around. | 1994-12-20
row 8 : 9 | 1 | "dee dee runs away" | dee dee has been waiting to go to a monster truck show p1w. but alfie and goo's baseball team makes it to the tournament and everyone forgets about the monster truck show. dee dee feels ignored and runs away from home with harry and donnell. it's up to alfie and goo to try and convince him to come home. | 1994-12-28
row 9 : 10 | 1 | '"donnell's birthday party" | donnell is having a birthday party and brags about all the dancing and cool people who will be there. harry says that he knows how to dance so dee dee feels left out because he doesn't know how to dance. later on, harry admits to dee dee alone that he can't dance either and only lied so he doesn't get teased by donnell. so, they ask alfie to help them learn how to dance. he refuses to help because dee dee past_ref told on him to roger about his and goo's plans to cheat on their math quiz. alfie eventually agrees, after melanie threatens to refuse to help him with his math homework. soon dee dee and harry learn donnell's secret and were forced to teach him how to dance. after the party, dee dee tells alfie about it and finds out that he knew donnell was a liar. | 1995-1-5
row 10 : 11 | 1 | "alfie's birthday party" | goo and melanie pretend they are dating and they leave alfie out of everything. he ends up bored and starts hanging out with dee dee and his friends. however, it just isn't the same without goo. later on, alfie learns about the surprise birthday party that goo and melanie had been planning with everyone else (except for dee dee, who couldn't know since he would've told). | 1995-1-19
row 11 : 12 | 1 | "candy sale" | alfie and goo are selling candy to make money for some expensive jackets, but they are not having any luck. however, when dee dee start helping them sell candy, they start to make money and asks him to help them out. soon goo and alfie finds themselves confronted by melanie, deonne, harry and donnell for dee dee's share of the money. they soon learn the boys have used the money to buy 3 expensive jackets for themselves and dee dee as a token of their gratitude. they quickly apologize to alfie and goo for their quick judgment. | 1995-1-26
row 12 : 13 | 1 | "the big bully" | dee dee gets beat up at school and his friends try to teach him how to fight back. goo, however, tells him to bluff, but the plan backfires and dee dee gets hit because of it. when alfie confronts the bully, he learns that dee dee was picked on by a girl. alfie and goo decide to confront her. however, when some of their classmates, who happen to be the girls' siblings, learn they are bullying their sister, they intervene. | 1995-2-2
*/
columns: ['series #', 'season #', 'title', 'notes', 'original air date']
Q: how many people stayed at least 3 years in office?
<output>

In [6]:
result.iloc[0,-1]

'Output: Decompose:  \n- #1: The table provided is about a cycling competition (UCI ProTour), not related to the USL A-League or any football/soccer team.  \n- #2: The table caption is "Portland Timbers (2001–10)", which refers to a soccer team, specifically in the USL A-League.  \n- #3: However, the table data provided does not contain any information about years when the Portland Timbers were part of the USL A-League.  \n- #4: The years 2001–10 in the caption may refer to the team\'s active years, but the table data (cyclists, teams, times, points) does not support any direct link to the USL A-League or its timeline.  \n- #5: There is no data in the table about the team\'s participation in the USL A-League, nor any year listed explicitly.  \n\nFinal Answer: Therefore, the answer is: "unknown"'

In [ ]:
from tqdm.notebook import tqdm
import json
def load_niat_dataset( 
    dataset_path,
    tag="test",
    first_n=-1,
):
    """Load niat JSONL (latest format) and normalize fields for CoT pipeline.

    - Adds incremental id: f"{tag}-{i}"
    - Initializes empty chain list per sample
    - Builds `table_text` from `table.header` + `table.rows` when available
    - Sets `table_caption` from `table.page_title` when available
    - Ensures both `question` and `statement` exist for compatibility
    - Respects `first_n` to limit number of loaded lines
    """
    dataset = []
    if first_n != -1:
        all_lines = []
        for line in open(dataset_path):
            all_lines.append(line)
            if len(all_lines) >= first_n:
                break
    else:
        all_lines = open(dataset_path).readlines()

    for i, line in tqdm(enumerate(all_lines), total=len(all_lines), desc=f"Loading niat-{tag} dataset"):
        info = json.loads(line)

        # Basic identifiers
        info["id"] = f"{tag}-{i}"
        info["chain"] = []

        # Derive table_text if not present
        if "table_text" not in info:
            info['table_text'] = info.get('table_rows', [])

        # Derive table_caption if not present
        if "table_caption" not in info:
            caption = info.get("table_tile", "")
            info["table_caption"] = caption

        dataset.append(info)
    return dataset

result = load_niat_dataset('../datasets/NIAT/sampled_qa_pairs_4000_fixed.json')

In [67]:
result = pd.read_csv('/data/workspace/yanmy/SPARQ/schedule_pipeline/tmp/niat_test/final_results.csv')

In [68]:
result

,table_id,dataset_name,table_structure,table_format,table_title,table_rows,html_table,question,answer,instruction,predict
0,WTQ_transpose_38,WTQ,horizontal,HTML,Willy DeVille discography,"[['Year', 'Year', '1981', '1993', '1995', '199...",<table border='1'>\n <tr>\n <td>Year</td>\...,What is the peak chart position for 'Cadillac ...,—,You are an expert on table data.\nYou must use...,"['1. Decompose:\n - #1: Identify the song ""..."
1,AIT-QA_tab-37,AIT-QA,hierarchical,HTML,NaN,"[['', ' ', ' ', 'Class or Craft', 'Employees ...","<table border=""1"" class=""dataframe"">\n <thead...",How many Ground School Instructors are represe...,10,You are an expert on table data.\nYou must use...,['Decompose:\n - #1: Find the row where \'c...
2,WTQ_transpose_161,WTQ,horizontal,HTML,Liquefied natural gas,"[['Plant Name', 'Qatargas II', 'Arzew GL4Z', '...",<table border='1'>\n <tr>\n <td>Plant Name...,How much capacity does Sakhalin II have?,9.6,You are an expert on table data.\nYou must use...,['Decompose:\n - #1: Find the row where \'p...
3,WTQ_transpose_94,WTQ,horizontal,HTML,Jim Glaser,"[['Year', 'Year', '1968', 'singles only', 'sin...",<table border='1'>\n <tr>\n <td>Year</td>\...,What was the CAN Country chart position for 'I...,—,You are an expert on table data.\nYou must use...,"['1. Decompose:\n - #1: Identify the song ""..."
4,WTQ_203-csv_121,WTQ,vertical,HTML,1947–48 in Swedish football,"[['name', 'pos.', 'caps', 'goals', 'club'], ['...","<table border=""1"" class=""wikitable"">\n<tr>\n<t...",Which club does Rune 'Killing' Emanuelsson pla...,IFK Göteborg,You are an expert on table data.\nYou must use...,['1. Decompose:\n - #1: Find the row where ...
...,...,...,...,...,...,...,...,...,...,...,...
3984,HiTab_129_totto15747-4,HiTab,hierarchical,HTML,studio albums,"[[' title ', ' album details ', ' peak chart p...","<table border=""1"" cellspacing=""0"">\n<tr> <td r...",Which album was released in June 1972?,Free at Last,You are an expert on table data.\nYou must use...,['1. Decompose:\n - #1: Find the row where ...
3985,WTQ_transpose_171,WTQ,horizontal,HTML,Primary schools in Hertsmere,"[['Name', 'Ashfield', 'Bournehall', 'Bushey He...",<table border='1'>\n <tr>\n <td>Name</td>\...,What is the Ofsted number for Highwood?,117089,You are an expert on table data.\nYou must use...,['Decompose:\n - #1: Find the row where nam...
3986,WTQ_transpose_78,WTQ,horizontal,HTML,Leinster Intermediate Club Football Championship,"[['', '1', '', '', '', '', '', '', '', ''], ['...",<table border='1'>\n <tr>\n <td></td>\n ...,Which team won in 2011?,Greystones,You are an expert on table data.\nYou must use...,['1. Decompose:\n - #1: Identify the column...
3987,WTQ_transpose_180,WTQ,horizontal,HTML,Christopher Eccleston,"[['Year', '1991', '1992', '1993', '1994', '199...",<table border='1'>\n <tr>\n <td>Year</td>\...,What was the role played in the 1991 film 'Let...,Derek Bentley,You are an expert on table data.\nYou must use...,['Decompose:\n - #1: Identify the film \'Le...
3988,WTQ_transpose_194,WTQ,horizontal,HTML,List of PWG World Tag Team Champions,"[['Rank [3]', '01 !1', '02 !1', '03 !3', '04 !...",<table border='1'>\n <tr>\n <td>Rank [3]</...,How many reigns does Excalibur have?,1,You are an expert on table data.\nYou must use...,['Decompose:\n - #1: Identify the row where...

In [3]:
result = pd.read_csv('/data/workspace/yanmy/SPARQ/schedule_pipeline/tmp/niat_test/final_results.csv')

In [4]:
import re
from utils.evaluator import Evaluator

def niat_match_func_robust(pred, gold):
    """
    独立评估函数：对比预测答案与标准答案 (NIAT Robust Version)。
    
    Args:
        pred (str): 预测答案字符串 (e.g. '2. Final Answer: The answer is: "IFK Göteborg"')
        gold (str): 标准答案字符串 (e.g. 'IFK Göteborg')
    
    Returns:
        bool: True 表示匹配正确
    """
    # 1. Parsing: 解析 "The answer is:" 之后的真实答案
    if isinstance(pred, str):
        # 使用 Ignore Case 匹配，更加鲁棒
        match = re.search(r'The answer is:\s*(.+)', pred, re.IGNORECASE)
        if match:
            pred = match.group(1)
            
    # 2. Evaluation: 复用 Evaluator 中的 WikiTQ 逻辑 (eval_ex_match)
    # 传入 allow_semantic=True 以支持归一化和语义匹配
    # 传入 question="" 以绕过 Evaluator 中的 assertion，同时跳过仅针对 boolean/choice 的特殊逻辑
    return Evaluator().eval_ex_match(pred, gold, allow_semantic=True, question="")

def calculate_niat_accuracy(preds, golds):
    """
    计算准确率 (Accuracy)。
    
    Args:
        preds (List[str]): 预测答案列表
        golds (List[str]): 标准答案列表
    
    Returns:
        float: Accuracy (0.0 ~ 1.0)
    """
    if len(preds) != len(golds):
        print(f"Warning: preds count ({len(preds)}) != golds count ({len(golds)})")
        
    correct_count = 0
    total_count = 0
    
    for p, g in zip(preds, golds):
        try:
            if niat_match_func_robust(p, g):
                correct_count += 1
        except Exception as e:
            print(f"Error evaluating pair: p='{p}', g='{g}'. Error: {e}")
        finally:
            total_count += 1
            
    if total_count == 0:
        return 0.0
        
    return correct_count / total_count

/home/aizoo/miniconda3/lib/python3.13/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/home/aizoo/miniconda3/lib/python3.13/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

In [5]:
preds = [eval(result.iloc[i,-1])[0].split('the answer is:')[-1][:200].strip().replace('"','') for i in range(len(result))]
golds = result.iloc[:,-3].to_list()

In [6]:
calculate_niat_accuracy(preds,golds)

0.6658310353472048

In [73]:
print(result.iloc[0,-2])

You are an expert on table data.
You must use the table data and the additional evidence to answer the given question.

Procedure:
- Divide the main statement into sub-tasks and answer each sub-task
- Based on the answers, provide the final answer to the question

**NOTE**
Please be extremely careful, pause, make sure all instructions have been followed and only then output the answer

Response Format:
Begin your response with 'Output: ' and always include the following:
- Decompose: Divide the main question into sub-tasks and answer each sub-task
- Final Answer: Strictly output as a short phrase starting by `therefore, the answer is: "AnswerName1", "AnswerName2"...` form, no other form

- Read the question carefully, understand, and return what the question asks.
- Be careful, make sure you have followed all instructions and only then return the output.
```
<input>
table caption: Employee Labor Contracts
/*
col : group | union | class_or_craft | employees | contract_date
row 0 : Mainline | Allied Pilots Association | Pilots | 13200 | 2020
row 1 : Mainline | APFA | Flight Attendants | 24900 | 2019
row 2 : Envoy | TWU | Ground School Instructors | 10 | 2019
*/
columns: ['group', 'union', 'class_or_craft', 'employees', 'contract_date']
Q: How many Ground School Instructors are represented by TWU?
<output>
Use the table to answer the question.
1. Decompose:
    - #1: Find rows where class_or_craft = Ground School Instructors AND union = TWU
    - #2: employees for that row = 10
2. Final Answer: Therefore, the answer is: "10"

<input>
table caption: LNG Plants Worldwide
/*
col : plant_name | country | startup_date | capacity
row 0 : Qatargas II | Qatar | 2009 | 7.8
row 1 : Nigeria LNG | Nigeria | 1999 | 23.5
row 2 : Sakhalin II | Russia | 2009 | 9.6
*/
columns: ['plant_name', 'country', 'startup_date', 'capacity']
Q: How much capacity does Sakhalin II have?
<output>
1. Decompose:
    - #1: Find the row where plant_name = Sakhalin II
    - #2: capacity for that row = 9.6
2. Final Answer: Therefore, the answer is: "9.6"

<input>
/*
col : draw | country | artist | song | place | points
row 0 : 1 | Yugoslavia | Extra Nena | Ljubim te pesmama | 13 | 44
row 1 : 2 | France | Kali | Monté la rivié | 8 | 73
row 2 : 3 | Denmark | Lotte Nilsson | Alt det som ingen ser | 12 | 47
*/
columns: ['draw', 'country', 'artist', 'song', 'place', 'points']
Q: In what position did Denmark finish in the Eurovision Song Contest 1992?
<output>

Here is an additional evidence to help the answering process.
Additional Evidence:
/*
col : country | place
row 0 : Denmark | 12
*/
Using the table and the additional evidence to answer the question
1. Decompose:
    - #1: Find the row where country = Denmark
    - #2: place for Denmark = 12
2. Final Answer: Therefore, the answer is: "12"
```

<input>
CREATE TABLE Willy_DeVille_discography(
	row_id int,
	`year` text,
	`year_1` text,
	`1981` text,
	`1993` text,
	`1995` text,
	`1996` text,
	`1996_1` text,
	`1996_2` text,
	`1996_3` text,
	`1997` text,
	`1997_1` text,
	`1997_2` text,
	`1999` text,
	`2001` text,
	`2003` text,
	`2005` text,
	`2009` text,
	`"—" denotes releases that did not chart.` text)
/*
SELECT * FROM w;
 row_id                 year  year_1         1981                     1993                              1995                               1996                           1996_1         1996_2                1996_3              1997                  1997_1                   1997_2               1999                                       2001          2003         2005                      2009 "—" denotes releases that did not chart.
      0                Title   Title Savoir faire Spanish Stroll 1977-1987 Les inoubliables de Willy DeVille Love & Emotion: The Atlantic Years Mink/Willy DeVille Greatest Hits Spanish Stroll Best of Willy DeVille His Greatest Hits Premium Gold Collection The Best of Mink DeVille Collection légende Cadillac Walk: The Mink DeVille Collection Greatest Hits Mink DeVille Introducing Willy DeVille "—" denotes releases that did not chart.
      1 Peak chart positions   Label            —                        —                                 —                                 54                                —              —                     —                 —                       —                        —                  —                                          —             —            —                         — "—" denotes releases that did not chart.
      2                Label  Artist      Capitol             Disky, Raven                            Wagram                           Atlantic                              EMI          Disky                Arcade            Arcade                     EMI                      EMI             Wagram                                    Capitol           EMI        Disky                      Edel "—" denotes releases that did not chart.
      3               Artist GER [6] Mink DeVille             Mink DeVille                     Willy DeVille                  Mink DeVille[C 1]                     Mink DeVille   Mink DeVille         Willy DeVille      Mink DeVille            Mink DeVille             Mink DeVille      Willy DeVille                               Mink DeVille  Mink DeVille Mink DeVille             Willy DeVille "—" denotes releases that did not chart.
*/
columns: ['row_id', 'year', 'year_1', '1981', '1993', '1995', '1996', '1996_1', '1996_2', '1996_3', '1997', '1997_1', '1997_2', '1999', '2001', '2003', '2005', '2009', '"—" denotes releases that did not chart.']
Q: What is the peak chart position for 'Cadillac Walk: The Mink DeVille Collection'?
<output>